remote_theme: pages-themes/tactile@v0.2.0
title: Adit Reddy
description: Computer Science Engineering @ George Mason University | Java/C/Python Developer | Programmer | AI/Machine Learning enthusiast | Data Analytics | Quantative Analyst
google_analytics: 
show_downloads: true
